name: Publish Python Package

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the version from the latest tag
      id: get_version
      run: |
        echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Update version in setup.py
      run: |
        VERSION=${{ env.VERSION }}
        # Strip the leading 'v' from the tag
        VERSION=${VERSION#v}
        sed -i "s/version='.*'/version='$VERSION'/" setup.py

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
