name: Create Pull Request

on: [push]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  

    - name: Run tests
      run: |
        pytest